### ISSUE TITLE
Viability of making eta port of Vinyl and Frames

### ISSUE THREAD

**Issue by codygman** [typelead/eta#152]
After reading that not every Haskell extension will be made available in Eta I'm thinking that making a port of the Vinyl and Frames libraries in eta will not be aligned with the goals of Eta.

Am I correct in assuming this? It would require many language extensions that Eta's design goals might not find important such as:

```
{-# LANGUAGE ConstraintKinds       #-}
{-# LANGUAGE DataKinds             #-}
{-# LANGUAGE FlexibleContexts      #-}
{-# LANGUAGE FlexibleInstances     #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE ExplicitNamespaces #-}
{-# LANGUAGE PolyKinds  #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE BangPatterns          #-}
{-# LANGUAGE CPP                   #-}
```

Thanks.

**Comment by rahulmutt** [comment]
I find most of those extensions important :) Where did you get the feeling that Eta's design goals are opposed to extensions? I can clarify it so that other people don't get confused.

Btw if you install `eta` and `epm` and run `epm install vinyl`, you'll be able to compile it right now.

 You can also compile almost all dependencies of `Frames` and the only reason you can't compile `Frames` itself is that it depends on TemplateHaskell. TemplateHaskell is a work item, see #130.

**Comment by rahulmutt** [comment]
If you're interesting in making `Frames` compile and using it without TemplateHaskell for now, I'll accepts a patch in [eta-hackage](https://github.com/typelead/eta-hackage).

**Comment by codygman** [comment]
Also, I got the wrong idea that Eta was extension averse from this Reddit thread: https://www.reddit.com/r/haskell/comments/5cdgxa/ghcvm_the_ghc_haskell_to_jvm_compiler_was_renamed/

**Comment by rahulmutt** [comment]
We can take the discussion on Gitter if you really want to know, but in short, that entire post is misguided.

I think the issue is cleared up. The answer is yes, Frames and vinyl are game for Eta, but you'll just have to wait for a bit while we work out the Template Haskell implementation.
