### ISSUE TITLE
Generate Java bytecode at runtime for the interpreter

### ISSUE THREAD

**Issue by DemiMarie** [typelead/eta#167]
Instead of generating a GHC-like bytecode that is interpreted by a Java program, Eta can generate Java bytecode which is directly executed by the JVM.

**Comment by rahulmutt** [comment]
Yes and this would be much faster, and you might as well compilation with `-O0` in this case. The GHCi bytecodes were specifically designed to be relinkable with bytecode-compiled closures w/o recompiling the bytecode. The normal codegen isn't so friendly for that. But because this the JVM and we can use a custom classloader to redefine classes at runtime, this may not be a bad idea. We'll have to think through it some more.

**Comment by rahulmutt** [comment]
Closing this as the question has been answered.
