### ISSUE TITLE
Program crashes with "newBoundTask: RTS is not initialized; call hsInit() first" when Spark calls an Eta handler

### ISSUE THREAD

**Issue by tatut** [typelead/eta#172]
Using Spark (http://sparkjava.com/) and registering a simple handler starts up, but the program crashes with an error when calling the registered handler:
newBoundTask: RTS is not initialized; call hsInit() first

Relevant code:
```haskell
{-# LANGUAGE OverloadedStrings, MagicHash, TypeFamilies, DataKinds #-}
module Main where

import Java

data {-# CLASS "spark.Spark" #-} Spark = Spark (Object# Spark)
data {-# CLASS "spark.Route" #-} Route = Route (Object# Route)
data {-# CLASS "spark.Request" #-} Request = Request (Object# Request)
data {-# CLASS "spark.Response" #-} Response = Response (Object# Response)

type Handler = Request -> Response -> Java Route Object

foreign import java unsafe "@wrapper handle"
  mkRoute :: Handler -> Route

foreign import java unsafe "@static spark.Spark.get"
  get :: String -> Route -> IO ()

hello :: Handler
hello req res = return $ superCast ("foo" :: JString)

main = do
  get "/hello" (mkRoute hello)
```

**Comment by rahulmutt** [comment]
I ran a trace to figure out what's happening:
1) On main thread, Eta RTS is initialised and main function is run to setup the routes.
2) Parallelly, a Thread is spawned for the jetty server.
3) On main thread, Eta RTS is reinitialised.
4) You go to /dummy, you try to execute the handler, but the RTS has already been de-initialized, hence crash.

Simple fix: initialise the RTS if it hasn't been initialised instead of crashing. I'm sure GHC people had a good reason for this behavior, so I'll investigate a bit.

I'll push it out tomorrow.

**Comment by tatut** [comment]
Should RTS be initialized in a static initializer block of the main class.
And not de-initialized until the JVM exits with a Runtime.addShutdownHook()

That should guarantee that everything is up and running when after the main class has been loaded by the JVM and that nothing is de-initialized too early.

**Comment by rahulmutt** [comment]
@tatut By default, all exported classes contain a static initialiser block that initialises the RTS if it hasn't been already. I just pushed a fix that re-initialized in case it's not initialised. I took a lot at the initialisation code closely and we don't lose much from re-initializing.

It's working fine now when I tested locally. Carry on with your work and let me know if anymore problems come up :)
