### ISSUE TITLE
compiler should generate correct code not only with optimization

### ISSUE THREAD

**Issue by Ingo60** [typelead/eta#198]
I checked direct and indirect tail recursion with eta 0.0.5
Here are the respective source codes:

https://gist.github.com/Ingo60/396a40a73a4f5b387d1bb76af30d4ac4 (indirect tail recursion)
https://gist.github.com/Ingo60/36ee203caa64f21f52b148188037a9e7 (direct tail recursion)

I found that without optimization, the programs fail with stack overflow.
When I add `-O` , the direct tail recursion works.
One needs `-O2` apparently to make indirect tail recursion work.

Since eta is obviously capable of creating correct code in both cases, I suggest to do that always, as the correctness of a program should not depend on the optimization level it is compiled with.

**Comment by rahulmutt** [comment]
Thanks for trying out different cases of tail recursion! These examples will be great to test whether the future changes that are planned actually work as intended. 

This is not really a correctness problem and more of the current limitation of how Eta deals relies on the JVM stack, so we are effectively bound by the default JVM stack size which turns out to be ~1MB on most platforms. A lot of the current limitations can be overcome once #23 is implemented, since we can allow the stack size to be infinite (which is GHC's default implementation in the recent versions, see [this GHC Trac ticket](https://ghc.haskell.org/trac/ghc/ticket/8189)).

In practice, most of the libraries you compile with will be optimised by default and you will most likely optimise any applications you would work on, so relying on `-O2` to solve the stack issues is not such a bad thing. I could of course remove all these optimisation flags and just do `-O2` by default so that users don't deal with the stack issues. 

We may have to go with that option if #23's implementation doesn't pan out as expected.

**Comment by rahulmutt** [comment]
Moreover, the loopfication optimisation, the primary optimisation responsible for coverting tail calls to loops only occurs at `-O1` (equivalent to `-O2`), so it's not surprising that it blows the stack without optimisation since it'll be calling itself over and over again.

**Comment by rahulmutt** [comment]
Closing, since the question has been answered, and the main issue raised in this issue is discussed in #200.
