### ISSUE TITLE
Green threads

### ISSUE THREAD

**Issue by agocorona** [typelead/eta#239]

**Comment by rahulmutt** [comment]
Current work is going on in the `context-switch` branch.

**Comment by agocorona** [comment]
Great. How it goes? It is a pity but I can not help since I know little about Java or even GHC internals.
 
Is it possible to run some form of forkIO or forkOS now?

**Comment by rahulmutt** [comment]
We got a prototype implementation on the `context-switch` branch that you can take a look at, but it's generating too much bytecode right now to be practical and in some cases generates huge class files (for heavily inlined functions) and triggers verify errors with `codec-jvm` that are hard to trace. Have to see if I can find a smaller reproduction case to fix that.

So the current plan is to get the first release out (April 30) and then resume work on the concurrent runtime soon after, by making the generated bytecode optimal removing redundancy.

If you're interesting in helping out with that part of the runtime, by all means you're welcome. I'd be happy to share the necessary details you'll need.

**Comment by jneira** [comment]
Hi, have you take a look to [quasar](https://github.com/puniverse/quasar)? Although maybe it is not applicable to eta at all ....

**Comment by rahulmutt** [comment]
@jneira Yes, we have taken a look at Quasar, but many people (such as Charles Nutter and Daniel Spiewak) suggest that we avoid the green thread route because it kills JIT compilation. We may give it a try at some point and benchmark to see what benefits we actually get, but for now we're looking at a refactoring of the concurrent RTS to use something like thread pools.

**Comment by rahulmutt** [comment]
The refactoring of the concurrent RTS is done and it uses dynamic thread pools with configurable maximum size.
