### ISSUE TITLE
Error runing etlas repl in a project with java source files

### ISSUE THREAD

**Issue by jneira** [typelead/eta#805]
* Trying to run `etlas repl` in `wai-servlet` i got this error:
```
target ‘java\Utils.java’ is not a module name or a source file
Prelude>
```
* The repl starts with no modules loaded (and you cant load them with :m)

**Comment by rahulmutt** [comment]
@jneira It would be helpful if #778 is resolved since the logic for implementing this requires knowing whether Java sources have changed and whether recompiling/reloading the class files is required. Can you take a look at that one?

**Comment by jneira** [comment]
Hi, strating to look at this, the first issue is `.java` files [are not recognized as a valid "target" in interactive mode](https://github.com/typelead/eta/blob/master/compiler/Eta/Main/GHC.hs#L672-L703) (but they are valid in "make" mode), should we add java files as valid targets?

**Comment by rahulmutt** [comment]
In make mode, see here:

https://github.com/typelead/eta/blob/master/eta/Main.hs#L638-L642

Notice that all the non-Haskell-like source files are all collected and compiled separately and only then is guessTarget called on the remaining files. Couple things to do:

1) Take a look at GHC master and see if they've updated the logic to unify all the source types. Most likely it'll be the same since it doesn't make sense to add C files as a target since there's no cross-platform way to compile C files. It's a lot easier for us since Java/JVM tooling is cross-platform.
2) Add java-like files (.java, .class, .jar) as valid targets and handle them in the rest of the pipeline accordingly. Most importantly, make sure up-to-date checking is done properly.
