### ISSUE TITLE
Using Data.Text.IO.readFile throws intermitent "resource busy (file is locked)" in windows

### ISSUE THREAD

**Issue by jneira** [typelead/eta#916]
## Description

dhall-eta tests reads lot of dhall files using Data.Text.IO.readFile and some of the calls throws `path\to\file openFile: resource busy (file is locked)`
## Expected Behavior

All files should be readed correctly
## Actual Behavior

In windows i get occasionally
```
      Exception:
      ↳ ./../dhall-lang/Prelude/package.dhall
        ↳ ./../dhall-lang/Prelude/Integer/package.dhall
          ↳ ./../dhall-lang/Prelude/Integer/toDouble
      D:\ws\eta\dhall\dhall-eta\..\dhall-lang\Prelude\Integer\toDouble: openFile: resource busy (file is locked)
```
## Possible Fix

Maybe the locking is related with https://github.com/typelead/eta/issues/307?
## Steps to Reproduce

1. Checkout `dhall-eta` in a windows env
2. Run `etlas test`

## Context

Setup test suite for `dhall-eta`
## Your Environment

* local: windows with eta and etlas built from master
* Link to your project: https://github.com/eta-lang/dhall-eta

**Comment by jneira** [comment]
As [@rahulmutt suggested](https://github.com/typelead/eta/issues/915#issuecomment-449163595) in #915 the way to debuf the issue could be set
```
set ETA_JAVA_ARGS="-Deta.debug.exceptions=true -Deta.debug.exceptionsVerbose=true -Deta.debug.toFile=true"
```

**Comment by rahulmutt** [comment]
The only way you can get `openFile: resource busy (file is locked)` is if the internal file locking system (defined by these [two functions](https://github.com/typelead/eta/blob/master/libraries/base/java-utils/Utils.java#L457-L484) on the Java side) are not truly thread-safe as we expect them to be. The logic was implemented quite crudely using the `synchronized` keyword - I'll take another look and see if there are holes in the logic. The hanging you're observing on linux may also be caused by this since it only seems to happen in the concurrent setting. Let me see if I can come up with a multi-thread execution sequence that can cause this to happen.

**Comment by rahulmutt** [comment]
I'm not able to reproduce now after implementing c4aa436. Turns out the `BasicFileAttributes.fileKey()` API in Java 7 returns null on Windows so I make a separate key for Windows to use for locking.

**Comment by jneira** [comment]
It works now like a charm after c4aa436 so i think we could close this one. Thanks for the quick fix @rahulmutt
